# Generated by Django 5.2.4 on 2025-09-19 01:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='image_url',
        ),
        migrations.AddField(
            model_name='episode',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
